export const defaultCheckList: {
  id: number
  largeCategory: string
  mediumCategory: string
  smallCategory: string
  part: string
  detail: string
}[] = [
  {
    id: 1,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "",
    detail: "クラック・爆裂、タイルの浮き･ふくらみ箇所はないか",
  },
  {
    id: 2,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "ベランダ",
    detail: "ゴミ屋敷はないか",
  },
  {
    id: 3,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "階段・廊下",
    detail: "汚れ・放置物はないか",
  },
  {
    id: 4,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "掲示板",
    detail: "破損はないか",
  },
  {
    id: 5,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "集合郵便受",
    detail: "破損、無断退去、郵便物のあふれはないか",
  },
  {
    id: 6,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "照明器具",
    detail: "破損・点灯不良・汚れはないか",
  },
  {
    id: 7,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "樋",
    detail: "割れ・はずれはないか",
  },
  {
    id: 8,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "設備ボックス",
    detail: "破損・錆はないか",
  },
  {
    id: 9,
    largeCategory: "日常点検",
    mediumCategory: "建物",
    smallCategory: "",
    part: "EV",
    detail: "汚れ・ゴミはないか",
  },
  {
    id: 10,
    largeCategory: "日常点検",
    mediumCategory: "団地内道路",
    smallCategory: "",
    part: "舗装",
    detail: "舗装面の割れ穴・水溜りはないか",
  },
  {
    id: 11,
    largeCategory: "日常点検",
    mediumCategory: "団地内道路",
    smallCategory: "",
    part: "フェンス",
    detail: "破損・錆はないか",
  },
  {
    id: 12,
    largeCategory: "日常点検",
    mediumCategory: "団地内道路",
    smallCategory: "",
    part: "縁石",
    detail: "段差・隙間・倒れはないか",
  },
  {
    id: 13,
    largeCategory: "日常点検",
    mediumCategory: "団地内道路",
    smallCategory: "",
    part: "U字溝",
    detail: "ゴミなど詰まりはないか",
  },
  {
    id: 14,
    largeCategory: "日常点検",
    mediumCategory: "団地内道路",
    smallCategory: "",
    part: "グレーチング・桝・桝蓋",
    detail: "ズレ・がたつきはないか",
  },
  {
    id: 15,
    largeCategory: "日常点検",
    mediumCategory: "敷地",
    smallCategory: "",
    part: "不法施設･投棄",
    detail: "不法施設（猫小屋、倉庫）･投棄はないか",
  },
  {
    id: 16,
    largeCategory: "日常点検",
    mediumCategory: "敷地",
    smallCategory: "",
    part: "緑地",
    detail: "雑草･植栽の繁茂はないか",
  },
  {
    id: 17,
    largeCategory: "日常点検",
    mediumCategory: "敷地",
    smallCategory: "",
    part: "高木",
    detail: "枝折れ、落下、越境、根の浮きはないか",
  },
  {
    id: 18,
    largeCategory: "日常点検",
    mediumCategory: "敷地",
    smallCategory: "",
    part: "ﾍﾞﾝﾁ・ﾊﾟｰｺﾞﾗ",
    detail: "破損・錆、劣化はないか",
  },
  {
    id: 19,
    largeCategory: "日常点検",
    mediumCategory: "敷地",
    smallCategory: "",
    part: "ポール・照明器具",
    detail: "破損･点灯不良はないか",
  },
  {
    id: 20,
    largeCategory: "日常点検",
    mediumCategory: "駐車場",
    smallCategory: "",
    part: "区画線",
    detail: "区画線・番号は消えていないか",
  },
  {
    id: 21,
    largeCategory: "日常点検",
    mediumCategory: "駐車場",
    smallCategory: "",
    part: "舗装",
    detail: "舗装面の割れ・穴・水溜り車止めの破損はないか",
  },
  {
    id: 22,
    largeCategory: "日常点検",
    mediumCategory: "駐車場",
    smallCategory: "",
    part: "放置車両",
    detail: "放置車両･違法駐車はないか",
  },
  {
    id: 23,
    largeCategory: "日常点検",
    mediumCategory: "(その他箇所）",
    smallCategory: "",
    part: "駐輪場",
    detail: "破損・放置自転車はないか",
  },
  {
    id: 24,
    largeCategory: "日常点検",
    mediumCategory: "(その他箇所）",
    smallCategory: "",
    part: "ゴミ置場",
    detail: "破損･汚れ・放置ゴミはないか",
  },
  {
    id: 25,
    largeCategory: "日常点検",
    mediumCategory: "(その他箇所）",
    smallCategory: "",
    part: "給水施設",
    detail: "破損・錆･錠のはずれはないか",
  },
  {
    id: 26,
    largeCategory: "日常点検",
    mediumCategory: "その他",
    smallCategory: "",
    part: "",
    detail: "自治会・入居者等からの意見他",
  },
  {
    id: 27,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "外壁・窓周",
  },
  {
    id: 28,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "霧除け、庇",
  },
  {
    id: 29,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "ベランダ(設備等貫通部含）",
  },
  {
    id: 30,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "腰壁、床下・天井裏換気孔周",
  },
  {
    id: 31,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "階段室",
    detail: "階段庇",
  },
  {
    id: 32,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "階段室",
    detail: "踊場腰壁・手摺フレキ板",
  },
  {
    id: 33,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "階段室",
    detail: "階段手摺",
  },
  {
    id: 34,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "階段室",
    detail: "階段踏面、蹴上、あげ裏",
  },
  {
    id: 35,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁",
    part: "階段室",
    detail: "ノンスリップ",
  },
  {
    id: 36,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "仕上げ材",
    part: "吹き付",
    detail: "吹き付け塗材",
  },
  {
    id: 37,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "仕上げ材",
    part: "シール材",
    detail: "目地材（打継、誘発）",
  },
  {
    id: 38,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "仕上げ材",
    part: "タイル貼",
    detail: "",
  },
  {
    id: 39,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "仕上げ材",
    part: "モルタル塗",
    detail: "",
  },
  {
    id: 40,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "窓サッシ等",
    part: "",
    detail: "サッシ、扉類",
  },
  {
    id: 41,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "窓サッシ等",
    part: "",
    detail: "手摺",
  },
  {
    id: 42,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "窓サッシ等",
    part: "",
    detail: "ガラス",
  },
  {
    id: 43,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁取付材",
    part: "",
    detail: "換気口類、枠",
  },
  {
    id: 44,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁取付材",
    part: "",
    detail: "樋、通気管、排気塔",
  },
  {
    id: 45,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁取付材",
    part: "",
    detail: "電気引込取付金物",
  },
  {
    id: 46,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁取付材",
    part: "",
    detail: "配管類取付金物",
  },
  {
    id: 47,
    largeCategory: "外壁等",
    mediumCategory: "南外壁",
    smallCategory: "外壁取付材",
    part: "",
    detail: "吊金物",
  },
  {
    id: 48,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "外壁・窓周",
  },
  {
    id: 49,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "霧除け、庇",
  },
  {
    id: 50,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "ベランダ(設備等貫通部含）",
  },
  {
    id: 51,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "腰壁、床下・天井裏換気孔周",
  },
  {
    id: 52,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "階段室",
    detail: "階段庇",
  },
  {
    id: 53,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "階段室",
    detail: "踊場腰壁・手摺フレキ板",
  },
  {
    id: 54,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "階段室",
    detail: "階段手摺",
  },
  {
    id: 55,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "階段室",
    detail: "階段踏面、蹴上、あげ裏",
  },
  {
    id: 56,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁",
    part: "階段室",
    detail: "ノンスリップ",
  },
  {
    id: 57,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "仕上げ材",
    part: "吹き付",
    detail: "吹き付け塗材",
  },
  {
    id: 58,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "仕上げ材",
    part: "シール材",
    detail: "目地材（打継、誘発）",
  },
  {
    id: 59,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "仕上げ材",
    part: "タイル貼",
    detail: "",
  },
  {
    id: 60,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "仕上げ材",
    part: "モルタル塗",
    detail: "",
  },
  {
    id: 61,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "窓サッシ等",
    part: "",
    detail: "サッシ、扉類",
  },
  {
    id: 62,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "窓サッシ等",
    part: "",
    detail: "手摺",
  },
  {
    id: 63,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "窓サッシ等",
    part: "",
    detail: "ガラス",
  },
  {
    id: 64,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "換気口類、枠",
  },
  {
    id: 65,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "樋、通気管、排気塔",
  },
  {
    id: 66,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "電気引込取付金物",
  },
  {
    id: 67,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "配管類取付金物",
  },
  {
    id: 68,
    largeCategory: "外壁等",
    mediumCategory: "北壁面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "吊金物",
  },
  {
    id: 69,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "妻壁",
  },
  {
    id: 70,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "床下・天井裏換気孔周り",
  },
  {
    id: 71,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "仕上げ材",
    part: "吹き付",
    detail: "吹き付け塗材",
  },
  {
    id: 72,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "仕上げ材",
    part: "シール材",
    detail: "目地材（打継、誘発）",
  },
  {
    id: 73,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "仕上げ材",
    part: "タイル貼",
    detail: "タイル",
  },
  {
    id: 74,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "仕上げ材",
    part: "モルタル塗",
    detail: "",
  },
  {
    id: 75,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "換気口類、枠",
  },
  {
    id: 76,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "樋",
  },
  {
    id: 77,
    largeCategory: "外壁等",
    mediumCategory: "東妻面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "電気引込取付金物",
  },
  {
    id: 78,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "妻壁",
  },
  {
    id: 79,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "外壁",
    part: "躯体等",
    detail: "床下・天井裏換気孔周り",
  },
  {
    id: 80,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "仕上げ材",
    part: "吹き付",
    detail: "吹き付け塗材",
  },
  {
    id: 81,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "仕上げ材",
    part: "シール材",
    detail: "目地材（打継、誘発）",
  },
  {
    id: 82,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "仕上げ材",
    part: "タイル貼",
    detail: "タイル",
  },
  {
    id: 83,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "仕上げ材",
    part: "モルタル塗",
    detail: "",
  },
  {
    id: 84,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "換気口類、枠",
  },
  {
    id: 85,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "樋",
  },
  {
    id: 86,
    largeCategory: "外壁等",
    mediumCategory: "西妻面",
    smallCategory: "外壁取付材",
    part: "",
    detail: "電気引込取付金物",
  },
  {
    id: 87,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "アスファルト防水",
    part: "防水層",
    detail: "防水層",
  },
  {
    id: 88,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "アスファルト防水",
    part: "防水層",
    detail: "パラペット、笠木、鳩小屋・立上",
  },
  {
    id: 89,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "アスファルト防水",
    part: "防水層",
    detail: "ドレイン、どぶ周",
  },
  {
    id: 90,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "アスファルト防水",
    part: "防水層",
    detail: "目地、脱気装置",
  },
  {
    id: 91,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "アスファルト防水",
    part: "防水層",
    detail: "設備架台、モルタル笠木等",
  },
  {
    id: 92,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "シート防水系",
    part: "防水層",
    detail: "防水層",
  },
  {
    id: 93,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "シート防水系",
    part: "防水層",
    detail: "パラペット、笠木、鳩小屋・立上",
  },
  {
    id: 94,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "シート防水系",
    part: "防水層",
    detail: "ドレイン、どぶ周",
  },
  {
    id: 95,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "シート防水系",
    part: "防水層",
    detail: "目地、脱気装置",
  },
  {
    id: 96,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "シート防水系",
    part: "防水層",
    detail: "設備架台　　モルタル笠木等",
  },
  {
    id: 97,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "塗膜防水系",
    part: "防水層",
    detail: "防水層",
  },
  {
    id: 98,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "塗膜防水系",
    part: "防水層",
    detail: "パラペット、笠木、鳩小屋・立上",
  },
  {
    id: 99,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "塗膜防水系",
    part: "防水層",
    detail: "ドレイン、どぶ周",
  },
  {
    id: 100,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "塗膜防水系",
    part: "防水層",
    detail: "目地、脱気装置",
  },
  {
    id: 101,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "塗膜防水系",
    part: "防水層",
    detail: "設備架台　　モルタル笠木等",
  },
  {
    id: 102,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "勾配屋根（シングル葺）",
    part: "葺材",
    detail: "シングル材",
  },
  {
    id: 103,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "勾配屋根（シングル葺）",
    part: "葺材",
    detail: "棟押、軒先、けらば金物",
  },
  {
    id: 104,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "勾配屋根（シングル葺）",
    part: "葺材",
    detail: "軒樋、内樋、谷",
  },
  {
    id: 105,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "勾配屋根（瓦葺）",
    part: "葺材",
    detail: "瓦",
  },
  {
    id: 106,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "勾配屋根（瓦葺）",
    part: "葺材",
    detail: "瓦くぎ類",
  },
  {
    id: 107,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "勾配屋根（瓦葺）",
    part: "葺材",
    detail: "下地材、桟木",
  },
  {
    id: 108,
    largeCategory: "屋根・防水",
    mediumCategory: "住棟屋上",
    smallCategory: "勾配屋根（瓦葺）",
    part: "葺材",
    detail: "軒樋",
  },
  {
    id: 109,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "サッシ類",
    part: "サッシ",
    detail: "サッシ本体",
  },
  {
    id: 110,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "サッシ類",
    part: "サッシ",
    detail: "枠類",
  },
  {
    id: 111,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "サッシ類",
    part: "サッシ",
    detail: "水切",
  },
  {
    id: 112,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "サッシ類",
    part: "サッシ",
    detail: "パテ類",
  },
  {
    id: 113,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "扉類",
    part: "扉",
    detail: "扉本体、ヒンジ類",
  },
  {
    id: 114,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "扉類",
    part: "PS扉",
    detail: "扉本体、ヒンジ類",
  },
  {
    id: 115,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "扉類",
    part: "PS扉",
    detail: "郵便受",
  },
  {
    id: 116,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "手摺類",
    part: "アンカー",
    detail: "アンカー",
  },
  {
    id: 117,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "手摺類",
    part: "方立・竪桟",
    detail: "方立・竪桟",
  },
  {
    id: 118,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "手摺類",
    part: "横桟・笠木",
    detail: "横桟・笠木",
  },
  {
    id: 119,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "手摺類",
    part: "手摺子",
    detail: "手摺子",
  },
  {
    id: 120,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "手摺類",
    part: "隔板",
    detail: "隔板",
  },
  {
    id: 121,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "樋類",
    part: "軒樋",
    detail: "掴み金物類",
  },
  {
    id: 122,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "樋類",
    part: "竪樋",
    detail: "あんこう、ドレイン、",
  },
  {
    id: 123,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "樋類",
    part: "竪樋",
    detail: "接続チーズ、掃除口",
  },
  {
    id: 124,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外廊下",
    part: "",
    detail: "葺材本体",
  },
  {
    id: 125,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外廊下",
    part: "",
    detail: "小屋材",
  },
  {
    id: 126,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外廊下",
    part: "",
    detail: "柱・梁",
  },
  {
    id: 127,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外廊下",
    part: "",
    detail: "床モルタル等",
  },
  {
    id: 128,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外廊下",
    part: "",
    detail: "exJ",
  },
  {
    id: 129,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外階段",
    part: "",
    detail: "鉄骨本体",
  },
  {
    id: 130,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外階段",
    part: "",
    detail: "溶接箇所",
  },
  {
    id: 131,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外階段",
    part: "",
    detail: "ボルト類",
  },
  {
    id: 132,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外金物類",
    part: "",
    detail: "タラップ",
  },
  {
    id: 133,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外金物類",
    part: "",
    detail: "設備架台類",
  },
  {
    id: 134,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外金物類",
    part: "",
    detail: "アンテナ類",
  },
  {
    id: 135,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外金物類",
    part: "",
    detail: "物干金物類、吊ボルト類",
  },
  {
    id: 136,
    largeCategory: "塗装",
    mediumCategory: "外部",
    smallCategory: "屋外金物類",
    part: "",
    detail: "換気孔類",
  },
  {
    id: 137,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "給水管類",
    detail: "埋設管",
  },
  {
    id: 138,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "給水管類",
    detail: "引込露出管",
  },
  {
    id: 139,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "給水管類",
    detail: "竪管",
  },
  {
    id: 140,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "給水管類",
    detail: "メーター",
  },
  {
    id: 141,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "ポンプ類",
    detail: "ポンプ",
  },
  {
    id: 142,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "ポンプ類",
    detail: "制御盤類",
  },
  {
    id: 143,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "ポンプ類",
    detail: "受水槽",
  },
  {
    id: 144,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "ポンプ類",
    detail: "高架水槽",
  },
  {
    id: 145,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "排水管類",
    detail: "排水管類",
  },
  {
    id: 146,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "排水管類",
    detail: "マンホール",
  },
  {
    id: 147,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "給排水設備",
    part: "排水管類",
    detail: "排水桝",
  },
  {
    id: 148,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電灯幹線類",
    detail: "引込み",
  },
  {
    id: 149,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電灯幹線類",
    detail: "ハンドホール",
  },
  {
    id: 150,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電灯幹線類",
    detail: "ＥＰＳ",
  },
  {
    id: 151,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電灯幹線類",
    detail: "管",
  },
  {
    id: 152,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電灯幹線類",
    detail: "線ケーブル",
  },
  {
    id: 153,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "動力設備",
    detail: "引込み",
  },
  {
    id: 154,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "動力設備",
    detail: "ハンドホール",
  },
  {
    id: 155,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "動力設備",
    detail: "管",
  },
  {
    id: 156,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "動力設備",
    detail: "線ケーブル",
  },
  {
    id: 157,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電話設備",
    detail: "引込み",
  },
  {
    id: 158,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電話設備",
    detail: "ハンドホール",
  },
  {
    id: 159,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電話設備",
    detail: "ＥＰＳ",
  },
  {
    id: 160,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電話設備",
    detail: "管",
  },
  {
    id: 161,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "電話設備",
    detail: "線ケーブル",
  },
  {
    id: 162,
    largeCategory: "設備",
    mediumCategory: "",
    smallCategory: "電気設備",
    part: "アンテナ",
    detail: "",
  },
] as const
